spring.application.name=aaugp

spring.datasource.url=jdbc:postgresql://ep-hidden-feather-ap5fhjvy-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_HhNxoGDj4VK0&sslmode=require&channelBinding=require

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false



spring.jpa.open-in-view=false